spring:
  application:
    name: eureka
server:
  port: 8761
  context-path: /eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
logging:
  level:
    com.netflix: 'WARN'
    org.springframework.cloud: 'WARN'
